//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Cartelera
    {
        public int IdCartelera { get; set; }

        [Required(ErrorMessage = "Debe ingresar una Sede.")]
        [DisplayName("Sede")]
        public int IdSede { get; set; }

        [Required(ErrorMessage = "Debe ingresar una Película.")]
        [DisplayName("Pelicula")]
        public int IdPelicula { get; set; }

        [Required(ErrorMessage = "Debe ingresar una Hora de Inicio.")]
        [Range(1500, int.MaxValue, ErrorMessage = "La Hora Inicial debe ser mayor a las 15:00.")]
        [DisplayName("Hora de Inicio")]
        public int HoraInicio { get; set; }

        [Required(ErrorMessage = "Debe ingresar una Fecha de Inicio.")]
        [DisplayName("Inicio de cartelera")]
        public System.DateTime FechaInicio { get; set; }

        [Required(ErrorMessage = "Debe ingresar una Fecha Final.")]
        [DisplayName("Fin de Cartelera")]
        public System.DateTime FechaFin { get; set; }

        [Required(ErrorMessage = "Debe ingresar una Número de Sala.")]
        [DisplayName("Numero de Sala")]
        public int NumeroSala { get; set; }

        [Required(ErrorMessage = "Debe indicar una Versión.")]
        [DisplayName("Version")]
        public int IdVersion { get; set; }

        public bool Lunes { get; set; }
        public bool Martes { get; set; }
        public bool Miercoles { get; set; }
        public bool Jueves { get; set; }
        public bool Viernes { get; set; }
        public bool Sabado { get; set; }
        public bool Domingo { get; set; }

        [DisplayName("Fecha de Carga")]
        public System.DateTime FechaCarga { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual Sede Sede { get; set; }
        public virtual Versione Versione { get; set; }
    }
}
