//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class Reserva
    {
        public int IdReserva { get; set; }
        public int IdSede { get; set; }
        public int IdVersion { get; set; }
        public int IdPelicula { get; set; }
        [DisplayName("Inicio de la Funcion")]
        public System.DateTime FechaHoraInicio { get; set; }

        [Required (ErrorMessage="El campo 'Email' debe estar completo")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Debe ingresar un tipo de Documento")]
        public int IdTipoDocumento { get; set; }

        [Required(ErrorMessage = "El campo 'Número de Documento' debe estar completo")]
        [RegularExpression("[0-9]", ErrorMessage = "El campo 'Número de Documento' sólo debe contener números")]
        [DisplayName("Numero de Documento")]
        public string NumeroDocumento { get; set; }

        [Required(ErrorMessage = "El campo 'Cantidad de Entrdas' debe estar completo")]
        [DisplayName("Cantidad de Entradas")]
        public int CantidadEntradas { get; set; }

        [DisplayName("Fecha de Reserva")]
        public System.DateTime FechaCarga { get; set; }
        [DisplayName("Pelicula")]
        public virtual Pelicula Pelicula { get; set; }
        [DisplayName("Sede")]
        public virtual Sede Sede { get; set; }
        public virtual TiposDocumento TiposDocumento { get; set; }
        [DisplayName("Version")]
        public virtual Versione Versione { get; set; }
    }
}
