//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class Reserva
    {
        public int IdReserva { get; set; }

        [Required(ErrorMessage = "El campo 'Sede' debe estar completo")]
        public int IdSede { get; set; }
        [Required(ErrorMessage = "El campo 'Versión' debe estar completo")]
        public int IdVersion { get; set; }
        [Required(ErrorMessage = "El campo 'Película' debe estar completo")]
        public int IdPelicula { get; set; }
        [DisplayName("Inicio de la Función")]
        public System.DateTime FechaHoraInicio { get; set; }

        [Required(ErrorMessage = "El campo 'Email' debe estar completo")]
        [RegularExpression ("^[_a-z0-9-]+(.[_a-z0-9-]+)*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})$", ErrorMessage = "El e-mail no es válido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Debe ingresar un tipo de Documento")]
        public int IdTipoDocumento { get; set; }

        [Required(ErrorMessage = "El campo 'Número de Documento' debe estar completo")]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "El campo 'Número de Documento' sólo debe contener números")]
        [StringLength(20, ErrorMessage = "El número de documento puede tener máximo 20 dígitos")]
        [DisplayName("Numero de Documento")]
        public string NumeroDocumento { get; set; }

        [Required(ErrorMessage = "El campo 'Cantidad de Entradas' debe estar completo")]
        [Range (1, int.MaxValue, ErrorMessage = "Debe reservar al menos una entrada")]
        [DisplayName("Cantidad de Entradas")]
        public int CantidadEntradas { get; set; }

        [DisplayName("Fecha de Reserva")]
        public System.DateTime FechaCarga { get; set; }
        [DisplayName("Pelicula")]
        public virtual Pelicula Pelicula { get; set; }
        [DisplayName("Sede")]
        public virtual Sede Sede { get; set; }
        public virtual TiposDocumento TiposDocumento { get; set; }
        [DisplayName("Version")]
        public virtual Versione Versione { get; set; }
    }
}
