//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        [DisplayName("Nombre de Usuario")]
        public string NombreUsuario { get; set; }
        [DisplayName("Contraseña")]
        public string Password { get; set; }
    }
}
